_data/events.yml
I added some of the events happening over the summer. Ideally, we should integrate the google calendar so that someone doesn't have to do this by hand.
=> Added summer events

README.md
More complete documentation of how to add things for future reference (and people without much GitHub Pages experience), including where the photo albums are hosted, how to update the officers page, how to add newsletters, etc.
=> More details in readme about new features

_posts/2018-07-02-CS-Graduate-Student-Jobs.md
Just a short update to the Jobs FAQ based on Rajshree's feedback.
=> Corrected income info

_layouts/post.html, _posts/2018-04-09-Graduate-Student-Town-Hall-2017-Summary-and-Outcomes.md, _posts/2018-06-05-Finding-Housing-in-Boulder.md, _posts/2018-07-02-CS-Graduate-Student-Jobs.md, _posts/2018-3-28-Quality-of-Life-Survey-Summary.md, _posts/2018-4-2-Welcome-to-the-CSGSA.md, _posts/2018-4-4-News-from-the-Department-Executive-Committee.md
This is a pretty simple change. If you author a post and want credit, add an author field to the header and the byline will automatically be generated.
For example 
```
---
layout: post
author: Cecilia Mauceri
---
```
=> Add Bylines 

_layouts/base.html
The analytics account is the csgsa@colorado.edu account.
=> Add google analytics

_data/menu.yml, app-feedback.md
The page links to the CS Application Page with details for Fall 2022 and Jessie's post on the site for Fall 2021
We can add more details to the page to explain more about the program if so desired.
We can keep updating the page every cycle and add new links to posts or relevant site.
Testing Done: Tested Locally
A few sentences describing the overall goals of the pull request's commits.
Link to any issues that are relevant to this PR. This could be an issue this PR fixes.
If you answered No to question 1, go back and read the [instructions](.github/CONTRIBUTING.md) carefully.
Will be commenting screenshots for reference
=> Added new page "Application Feedback Program" under Resources

_posts/2018-06-05-Finding-Housing-in-Boulder.md
Added the new PPT in PDF form to assets fold. 
Updated the reference in the 'Finding Housing Post'
Some automatic formatting changes.
If you answered No to question 1, go back and read the [instructions](.github/CONTRIBUTING.md) carefully.
Do you want to add anything else? We :heart: to hear your opinions!
=> Update 'Finding Housing in Boulder' PPT with new one from S22 Open House

_posts/2018-06-05-Finding-Housing-in-Boulder.md, _posts/2021-04-03-fall-21-housing-survey-summary.md
A few sentences describing the overall goals of the pull request's commits.
Link to any issues that are relevant to this PR. This could be an issue this PR fixes.
If you answered No to question 1, go back and read the [instructions](.github/CONTRIBUTING.md) carefully.
Do you want to add anything else? We :heart: to hear your opinions!
=> Fall 2021 Housing Survey Summary

_data/menu.yml, professional-development.md
Added Professional Development page
Mentions the GPDC spin-off links to their LinkedIn page and their email. 
A screenshot will be added as a comment.
=> Add Professional Development page

_data/baic/schedule/summer22.yml
Added data for the Summer 22 Schedule
=> Add BAIC Summer 22 Schedule

_data/officers.yml
=> Fix Corey's Last name spelling mistake

_data/officers.yml
A few sentences describing the overall goals of the pull request's commits.
=> WIP officers.yml corrections

officers.md
- updated the roles as provided in the nomination form
=> updated the role of vice chair

funding.md
Added another link in the `Fellowship Resources` page under the `Resource and FAQ`  section
=> more funding sources

app-feedback.md
Update the appFeedback page to include the new form for application feedback 2023 (https://forms.office.com/r/YFuLBTEPdF)
=> Add updated 2023 application feedback form and information

_data/officers.yml
Removed GPSG rep and added to the alumni list
=> updated officers list

bylaws.md
Proposal: The bylaws shall be updated to include this fidelity on voting policy 
REPLACE:  
Charter Amendments: Changes to the charter may be proposed by the executive committee at any time. The deliberation period for any proposed change is 2 weeks. If any dissenting opinion is expressed by CSGSA members within the deliberation period, the Chair will call for a vote in the next meeting.  If no dissenting opinion is expressed or a majority of participants votes to adopt the change, the Chair will incorporate it. 
Charter updates, as described above, will also be conducted online for one week. 
WITH: 
Commonly Accepted Public Forum (CAPF):  
currently Slack 
This can change in future terms. This can be changed without bylaw amendment process given reasonable conditions (like Slack is …
=> Update bylaws.md with new bylaw change 2023

bylaws.md
Update the bylaws per the amendment process conducted in the second half of the Spring 2024 semester.
=> Bylaw Amendment Spring 24 #2

tentative_classes.md
Added Fall and Spring Tentative classes for 2025
=> Added Fall and Spring Tentative classes for 2025

_data/menu.yml, guide_student_insurance.md
Added Anthem Gold Student Health Insurance Plan (SHIP) and changed dependents
=> Added Anthem Gold Student Health Insurance Plan (SHIP)

_data/officers.yml, guide_student_insurance.md, people.md
Changed title for insurance and number of people in Grad Comm description
=> Changed title for insurance and number of people in Grad Comm
